import os
import json
import urllib.request
import urllib.parse
from dotenv import load_dotenv
from groq import Groq

# Load environment variables from .env file
load_dotenv()

# Initialize the Groq client
api_key = os.environ.get("GROQ_API_KEY")
if not api_key:
    raise ValueError("GROQ_API_KEY is not set in the environment or .env file")

client = Groq(api_key=api_key)

def call_laravel_filter(args: dict) -> list:
    """
    Calls the Laravel API endpoint to filter dishes based on arguments generated by Groq.
    """
    laravel_url = os.environ.get("LARAVEL_API_URL", "http://127.0.0.1:8000/api")
    url = f"{laravel_url}/ai/dishes/filter"
    
    # Filter out empty or null parameters
    clean_args = {k: v for k, v in args.items() if v is not None and v != ""}
    
    if clean_args:
        query_string = urllib.parse.urlencode(clean_args)
        url = f"{url}?{query_string}"
        
    print(f"Calling Laravel API: {url}")
    
    try:
        req = urllib.request.Request(
            url, 
            headers={
                "User-Agent": "SahaServe-Assistant/1.0", 
                "Accept": "application/json"
            }
        )
        with urllib.request.urlopen(req, timeout=10) as response:
            if response.status == 200:
                response_data = json.loads(response.read().decode('utf-8'))
                dishes = response_data.get("data", [])
                print(f"Laravel API successfully returned {len(dishes)} dishes.")
                return dishes
            else:
                print(f"Error from Laravel API: Status {response.status}")
                return []
    except Exception as e:
        print(f"Failed to call Laravel API: {e}")
        return []

def get_recommendation(user_request: str) -> dict:
    """
    Sends the user request and tools to Groq. Executes tools on behalf of Groq 
    by querying the Laravel database, and returns the final recommendations.
    """
    system_prompt = """You are a restaurant recommendation assistant for SahaServe.

You have access to our restaurant database via the `filter_dishes` tool. Whenever the user asks for recommendations, dishes, menu options, prices, categories, tags, or ingredients, you MUST use the `filter_dishes` tool to get live, up-to-date data.

You must ONLY recommend dishes that are present in the results returned by the `filter_dishes` tool. Never invent dishes.

You MUST always return a valid JSON object matching the following structure:
{
  "recommended_dishes": [
    {
      "id": 1,
      "name": "Dish Name",
      "price": 99.99,
      "reason": "Brief reason explaining why this dish matches the query."
    }
  ],
  "summary": "Friendly conversational summary of recommendations or greeting."
}

Rules:
- Never recommend dishes that do not exist or were not returned by the tool.
- Keep reasons short and relevant.
- Do not include markdown formatting or explanations outside of the JSON object."""

    tools = [
        {
            "type": "function",
            "function": {
                "name": "filter_dishes",
                "description": "Filter and search for dishes in the database based on keywords, category, tags, price constraints, and availability. Use this tool whenever the user asks for dishes, recommendations, prices, or menu options.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "Search keyword matching dish name or description (e.g., 'chicken', 'lamb')."
                        },
                        "category": {
                            "type": "string",
                            "description": "Filter by category name (e.g., 'Tagines', 'Couscous', 'Appetizers', 'Desserts', 'Drinks')."
                        },
                        "tags": {
                            "type": "string",
                            "description": "Comma-separated list of tag names to filter by (e.g., 'Vegetarian', 'Spicy', 'Gluten-Free', 'Traditional', 'Chef\'s Special')."
                        },
                        "min_price": {
                            "type": "number",
                            "description": "Minimum price filter."
                        },
                        "max_price": {
                            "type": "number",
                            "description": "Maximum price filter."
                        },
                        "is_available": {
                            "type": "string",
                            "description": "Availability filter ('true', 'false', or 'all'). Default is 'true'."
                        },
                        "limit": {
                            "type": "integer",
                            "description": "Limit the number of results returned."
                        },
                        "sort_by": {
                            "type": "string",
                            "enum": ["price", "name", "created_at"],
                            "description": "Sort the results by field."
                        },
                        "sort_order": {
                            "type": "string",
                            "enum": ["asc", "desc"],
                            "description": "Sort order (ascending or descending)."
                        }
                    },
                    "required": []
                }
            }
        }
    ]

    messages = [
        {
            "role": "system",
            "content": system_prompt,
        },
        {
            "role": "user",
            "content": user_request,
        }
    ]

    try:
        # 1. Call the model with user message and tools
        chat_completion = client.chat.completions.create(
            messages=messages,
            model="llama-3.3-70b-versatile",
            temperature=0.2,
            tools=tools,
            tool_choice="auto",
            response_format={"type": "json_object"}
        )
        
        response_message = chat_completion.choices[0].message
        tool_calls = getattr(response_message, "tool_calls", None)

        # 2. Check if the model wants to call a tool
        if tool_calls:
            # Add the assistant's message with tool calls to the thread
            messages.append(response_message)
            
            # Handle tool calls
            for tool_call in tool_calls:
                function_name = tool_call.function.name
                try:
                    function_args = json.loads(tool_call.function.arguments)
                except Exception:
                    function_args = {}
                
                if function_name == "filter_dishes":
                    # Execute search query in Laravel database
                    dishes_data = call_laravel_filter(function_args)
                    
                    # Append the tool response to the thread
                    messages.append({
                        "role": "tool",
                        "tool_call_id": tool_call.id,
                        "name": function_name,
                        "content": json.dumps(dishes_data)
                    })
            
            # 3. Request final completion from Groq with tool results included
            second_chat_completion = client.chat.completions.create(
                messages=messages,
                model="llama-3.3-70b-versatile",
                temperature=0.2,
                response_format={"type": "json_object"}
            )
            
            return json.loads(second_chat_completion.choices[0].message.content)
        
        else:
            # If no tools were called, directly return the model's response
            return json.loads(response_message.content)
            
    except Exception as e:
        return {
            "recommended_dishes": [],
            "summary": f"An error occurred while communicating with the Groq API: {e}"
        }
