import os
import json
import urllib.request
import urllib.parse
from dotenv import load_dotenv
from groq import Groq

# Load environment variables from .env file
load_dotenv()

# Initialize the Groq client
api_key = os.environ.get("GROQ_API_KEY")
if not api_key:
    raise ValueError("GROQ_API_KEY is not set in the environment or .env file")

client = Groq(api_key=api_key)

def format_dishes_for_model(dishes: list) -> list:
    return [
        {
            "id": dish.get("id"),
            "name": dish.get("name"),
            "description": dish.get("description"),
            "price": dish.get("price"),
            "category": (dish.get("category") or {}).get("name"),
            "tags": [tag.get("name") for tag in dish.get("tags", []) if isinstance(tag, dict)],
        }
        for dish in dishes
        if isinstance(dish, dict) and not dish.get("error")
    ]

def build_dish_response(dishes: list) -> dict:
    recommended_dishes = [
        {
            "id": dish.get("id"),
            "name": dish.get("name"),
            "price": dish.get("price"),
            "reason": "Matches your menu request.",
        }
        for dish in dishes[:5]
    ]

    dish_names = ", ".join(dish["name"] for dish in recommended_dishes if dish.get("name"))
    return {
        "recommended_dishes": recommended_dishes,
        "summary": f"I found these menu options for you: {dish_names}." if dish_names else "I could not find matching dishes on the current menu.",
    }

def response_needs_menu_fallback(response: dict) -> bool:
    if not isinstance(response, dict):
        return True

    recommended_dishes = response.get("recommended_dishes")
    summary = str(response.get("summary", "")).lower()
    failure_words = ["failed", "trouble", "error", "unavailable", "try again later", "could not retrieve", "not found", "no "]

    return not recommended_dishes and any(word in summary for word in failure_words)

def fallback_filter_args(user_request: str) -> dict:
    request = user_request.lower()

    tag_keywords = {
        "vegetarian": "Vegetarian",
        "vegan": "Vegetarian",
        "spicy": "Spicy",
        "traditional": "Traditional",
        "chef": "Chef's Special",
        "special": "Chef's Special",
    }
    for keyword, tag in tag_keywords.items():
        if keyword in request:
            return {"tags": tag, "limit": 5}

    category_keywords = {
        "tagine": "Tagines",
        "tagines": "Tagines",
        "couscous": "Couscous",
        "appetizer": "Appetizers",
        "starter": "Appetizers",
        "dessert": "Desserts",
        "drink": "Drinks",
        "tea": "Drinks",
    }
    for keyword, category in category_keywords.items():
        if keyword in request:
            return {"category": category, "limit": 5}

    return {"query": user_request, "limit": 5}

def get_menu_fallback(user_request: str) -> dict | None:
    dishes = format_dishes_for_model(call_laravel_filter(fallback_filter_args(user_request)))
    if not dishes:
        dishes = format_dishes_for_model(call_laravel_filter({"limit": 5}))

    return build_dish_response(dishes) if dishes else None

def call_laravel_filter(args: dict) -> list:
    """
    Calls the Laravel API endpoint to filter dishes based on arguments generated by Groq.
    """
    laravel_url = os.environ.get("LARAVEL_API_URL", "http://127.0.0.1:8000/api")
    url = f"{laravel_url}/ai/dishes/filter"
    
    # Filter out empty or null parameters
    clean_args = {k: v for k, v in args.items() if v is not None and v != ""}
    
    if clean_args:
        query_string = urllib.parse.urlencode(clean_args)
        url = f"{url}?{query_string}"
        
    print(f"[DEBUG] Calling Laravel API: {url}")
    
    try:
        req = urllib.request.Request(
            url, 
            headers={
                "User-Agent": "SahaServe-Assistant/1.0", 
                "Accept": "application/json"
            }
        )
        with urllib.request.urlopen(req, timeout=10) as response:
            raw = response.read().decode('utf-8')
            print(f"[DEBUG] Laravel raw response: {raw[:500]}")
            if response.status == 200:
                response_data = json.loads(raw)
                dishes = response_data.get("data", [])
                print(f"[DEBUG] Laravel API returned {len(dishes)} dishes.")
                return dishes
            else:
                print(f"[DEBUG] Error from Laravel API: Status {response.status}")
                return [{"error": f"Laravel returned status {response.status}"}]
    except Exception as e:
        print(f"[DEBUG] Failed to call Laravel API: {e}")
        return [{"error": f"Could not reach Laravel API: {e}"}]

def call_laravel_view_cart(auth_token: str) -> dict:
    if not auth_token or str(auth_token).strip() in ["", "null", "undefined", "None"]:
        return {"error": "User is not authenticated. Ask the user to log in."}
    
    laravel_url = os.environ.get("LARAVEL_API_URL", "http://127.0.0.1:8000/api")
    url = f"{laravel_url}/cart"
    
    try:
        req = urllib.request.Request(
            url, 
            headers={
                "User-Agent": "SahaServe-Assistant/1.0", 
                "Accept": "application/json",
                "Authorization": f"Bearer {auth_token}"
            }
        )
        with urllib.request.urlopen(req, timeout=10) as response:
            if response.status == 200:
                return json.loads(response.read().decode('utf-8'))
    except Exception as e:
        print(f"Failed to call Laravel view_cart: {e}")
        return {"error": str(e)}
    return {"error": "Unknown error occurred"}

def call_laravel_add_to_cart(dish_id: int, quantity: int, auth_token: str) -> dict:
    if not auth_token or str(auth_token).strip() in ["", "null", "undefined", "None"]:
        return {"error": "User is not authenticated. Ask the user to log in."}
        
    laravel_url = os.environ.get("LARAVEL_API_URL", "http://127.0.0.1:8000/api")
    url = f"{laravel_url}/cart"
    data = json.dumps({"dish_id": dish_id, "quantity": quantity}).encode('utf-8')
    
    try:
        req = urllib.request.Request(
            url,
            data=data,
            headers={
                "User-Agent": "SahaServe-Assistant/1.0", 
                "Accept": "application/json",
                "Content-Type": "application/json",
                "Authorization": f"Bearer {auth_token}"
            },
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=10) as response:
            if response.status in [200, 201]:
                return json.loads(response.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        error_body = e.read().decode('utf-8')
        return {"error": f"HTTP Error {e.code}: {error_body}"}
    except Exception as e:
        return {"error": str(e)}
    return {"error": "Unknown error occurred"}

def call_laravel_remove_from_cart(cart_item_id: int, auth_token: str) -> dict:
    if not auth_token or str(auth_token).strip() in ["", "null", "undefined", "None"]:
        return {"error": "User is not authenticated. Ask the user to log in."}
        
    laravel_url = os.environ.get("LARAVEL_API_URL", "http://127.0.0.1:8000/api")
    url = f"{laravel_url}/cart/items/{cart_item_id}"
    
    try:
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "SahaServe-Assistant/1.0", 
                "Accept": "application/json",
                "Authorization": f"Bearer {auth_token}"
            },
            method="DELETE"
        )
        with urllib.request.urlopen(req, timeout=10) as response:
            if response.status == 200:
                return json.loads(response.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        error_body = e.read().decode('utf-8')
        return {"error": f"HTTP Error {e.code}: {error_body}"}
    except Exception as e:
        return {"error": str(e)}
    return {"error": "Unknown error occurred"}

def get_recommendation(user_request: str, auth_token: str = None) -> dict:
    """
    Sends the user request and tools to Groq. Executes tools on behalf of Groq 
    by querying the Laravel database, and returns the final recommendations.
    """
    system_prompt = """You are a restaurant recommendation assistant for SahaServe.

You have access to our restaurant database via the `filter_dishes` tool. Whenever the user asks for recommendations, dishes, menu options, prices, categories, tags, or ingredients, you MUST use the `filter_dishes` tool to get live, up-to-date data.

You also have access to `view_cart`, `add_to_cart`, and `remove_from_cart`.
- If the user asks to add something to their cart, first find its `id` using `filter_dishes` (if you don't already know it), then call `add_to_cart` with that `dish_id`.
- If the user asks to remove an item from their cart, first call `view_cart` to see their cart items and find the `cart_item_id` of the item they want to remove, then call `remove_from_cart` with that ID.
- You must always inform the user of the result of their cart actions (e.g. success or failure).
- If an action requires authentication and fails with an error, ask the user to log in.

You MUST always return a valid JSON object matching the following structure:
{
  "recommended_dishes": [
    {
      "id": 1,
      "name": "Dish Name",
      "price": 99.99,
      "reason": "Brief reason explaining why this dish matches the query."
    }
  ],
  "summary": "Friendly conversational summary of recommendations, greeting, or confirmation of cart actions."
}

Rules:
- Never recommend dishes that do not exist or were not returned by the tool.
- Keep reasons short and relevant.
- Do not include markdown formatting or explanations outside of the JSON object."""

    tools = [
        {
            "type": "function",
            "function": {
                "name": "filter_dishes",
                "description": "Filter and search for dishes in the database based on keywords, category, tags, price constraints, and availability. Use this tool whenever the user asks for dishes, recommendations, prices, or menu options.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string", "description": "Search keyword matching dish name or description."},
                        "category": {"type": "string", "description": "Filter by category name."},
                        "tags": {"type": "string", "description": "Comma-separated list of tag names to filter by."},
                        "min_price": {"type": "number", "description": "Minimum price filter."},
                        "max_price": {"type": "number", "description": "Maximum price filter."},
                        "is_available": {"type": "string", "description": "Availability filter ('true', 'false', or 'all'). Default is 'true'."},
                        "limit": {"type": "integer", "description": "Limit the number of results returned."},
                        "sort_by": {"type": "string", "enum": ["price", "name", "created_at"], "description": "Sort the results by field."},
                        "sort_order": {"type": "string", "enum": ["asc", "desc"], "description": "Sort order (ascending or descending)."}
                    },
                    "required": []
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "view_cart",
                "description": "View the user's current cart and the items in it. Returns the cart contents including cart_item_ids.",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": []
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "add_to_cart",
                "description": "Add a specific dish to the user's cart.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "dish_id": {"type": "integer", "description": "The ID of the dish to add."},
                        "quantity": {"type": "integer", "description": "The quantity to add. Default is 1."}
                    },
                    "required": ["dish_id"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "remove_from_cart",
                "description": "Remove an item from the user's cart using its cart_item_id.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "cart_item_id": {"type": "integer", "description": "The ID of the cart item to remove. Use view_cart to find this."}
                    },
                    "required": ["cart_item_id"]
                }
            }
        }
    ]

    messages = [
        {
            "role": "system",
            "content": system_prompt,
        },
        {
            "role": "user",
            "content": user_request,
        }
    ]

    try:
        # 1. Call the model with user message and tools
        chat_completion = client.chat.completions.create(
            messages=messages,
            model="llama-3.3-70b-versatile",
            temperature=0.2,
            tools=tools,
            tool_choice="auto"
        )
        
        response_message = chat_completion.choices[0].message
        tool_calls = getattr(response_message, "tool_calls", None)

        # 2. Check if the model wants to call a tool
        if tool_calls:
            # Add the assistant's message with tool calls to the thread
            messages.append(response_message)
            menu_dishes = []
            used_cart_tool = False
            
            # Handle tool calls
            for tool_call in tool_calls:
                function_name = tool_call.function.name
                try:
                    function_args = json.loads(tool_call.function.arguments)
                except Exception:
                    function_args = {}
                
                tool_response = {}
                
                if function_name == "filter_dishes":
                    tool_response = call_laravel_filter(function_args)
                    formatted_dishes = format_dishes_for_model(tool_response)
                    menu_dishes.extend(formatted_dishes)
                    tool_response = formatted_dishes
                elif function_name == "view_cart":
                    used_cart_tool = True
                    tool_response = call_laravel_view_cart(auth_token)
                elif function_name == "add_to_cart":
                    used_cart_tool = True
                    dish_id = function_args.get("dish_id")
                    quantity = function_args.get("quantity", 1)
                    if dish_id:
                        tool_response = call_laravel_add_to_cart(dish_id, quantity, auth_token)
                    else:
                        tool_response = {"error": "dish_id is required."}
                elif function_name == "remove_from_cart":
                    used_cart_tool = True
                    cart_item_id = function_args.get("cart_item_id")
                    if cart_item_id:
                        tool_response = call_laravel_remove_from_cart(cart_item_id, auth_token)
                    else:
                        tool_response = {"error": "cart_item_id is required."}
                
                # Append the tool response to the thread
                messages.append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "name": function_name,
                    "content": json.dumps(tool_response)
                })
            
            # 3. Request final completion from Groq with tool results included
            try:
                second_chat_completion = client.chat.completions.create(
                    messages=messages,
                    model="llama-3.3-70b-versatile",
                    temperature=0.2,
                    response_format={"type": "json_object"}
                )
                final_response = json.loads(second_chat_completion.choices[0].message.content)

                if menu_dishes and not used_cart_tool and response_needs_menu_fallback(final_response):
                    return build_dish_response(menu_dishes)

                return final_response
            except Exception:
                if menu_dishes and not used_cart_tool:
                    return build_dish_response(menu_dishes)
                raise
        
        else:
            # If no tools were called, directly return the model's response
            final_response = json.loads(response_message.content)
            if response_needs_menu_fallback(final_response):
                fallback_response = get_menu_fallback(user_request)
                if fallback_response:
                    return fallback_response
            return final_response
            
    except Exception as e:
        fallback_response = get_menu_fallback(user_request)
        if fallback_response:
            return fallback_response

        return {
            "recommended_dishes": [],
            "summary": f"An error occurred while communicating with the Groq API: {e}"
        }
